### ISSUE TITLE
Python 3.6 support

### ISSUE THREAD

**Issue by rgieseke** [Zaharid/pandoc_static_katex#1]
Thanks a lot for this excellent tool! I got it running perfectly on 3.7 but ran into problems under 3.6, apparently due to changes in `subprocess.run` options, i got an error due to the "text" parameter.

I used a local copy with
```
 call = subprocess.run(
        ['npx', 'katex', '--no-throw-on-error', '--display-mode' if display else ''],
        input=code,
        check=True,
        stdout=PIPE,
        stderr=PIPE,
        universal_newlines=True
    )
```
Following ideas here: https://stackoverflow.com/questions/53209127/subprocess-unexpected-keyword-argument-capture-output/53209196

Not sure if there is a better solution. Happy to provide a pull request if you want!

For reference:
Python 3.6 docs: https://docs.python.org/3.6/library/subprocess.html#subprocess.run
Python 3.7 docs: https://docs.python.org/3.7/library/subprocess.html#subprocess.run

**Comment by Zaharid** [comment]
Hi, thanks for the report. I somehow only see it now.

I have fixed the incorrect metadata so as to specify the code works for Python 3.7. Like you say it is easy enough to get it to work for other versions, considering it is some 20 lines :D

**Comment by rgieseke** [comment]
Perfect :+1:
