### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified on subprocess.run

### ISSUE THREAD

**Issue by l0calh05t** [Zaharid/pandoc_static_katex#2]
`subprocess.run(['npx', ...], ...)` fails on Windows, since npx is not executable (npx.cmd however is). A potential solution may be to add `.cmd`  when `sys.platform.startswith('win32')`

**Comment by Zaharid** [comment]
Thanks. For some reason I was not "watching" this repo. I believe the current code should also work on Windows but have no immediate way to test it.

**Comment by l0calh05t** [comment]
I run into a different error on Windows now. The fix is simple so I posted a pull request #3
